Repository MidnightCommander/mc, pull requests merged in 2025-05, with the labels that each got.

#4700 Show size in 'bsize' format for dirs if's computed
  doc/man/mc.1.in
  src/filemanager/panel.c
Labels: area: core, prio: medium, state: approved

#4695 Add SortByVersion keymap
  lib/keybind.c
  lib/keybind.h
  misc/mc.default.keymap
  misc/mc.emacs.keymap
  misc/mc.vim.keymap
  src/filemanager/panel.c
Labels: area: keybind, prio: medium, state: approved

#4701 Ticket #4691: fix `\e` handling in `man2hlp` converter
  src/man2hlp/man2hlp.in
Labels: area: build, area: docs, prio: medium, state: approved

#4685 Enable filename scrolling by default and fix background color
  doc/man/mc.1.in
  doc/man/ru/mc.1.in
  lib/keybind.c
  lib/keybind.h
  misc/mc.default.keymap
  misc/mc.emacs.keymap
  misc/mc.vim.keymap
  src/filemanager/panel.c
  src/filemanager/panel.h
Labels: area: core, prio: medium, state: approved

#4708 Ticket #4707: fix `patchfs` for Z, xz, zst compressed diffs
  src/vfs/extfs/helpers/patchfs.in
Labels: area: vfs, prio: medium, state: approved

#4719 Ticket #4573: remove obsolete cppcheck & doxygen infrastructure
  .github/workflows/ci-ubuntu.yml
  .gitignore
  Makefile.am
  acinclude.m4
  configure.ac
  doc/Makefile.am
  doc/doxygen-include.am
  doc/doxygen.cfg
  lib/search/hex.c
  lib/tty/color-internal.c
  lib/tty/x11conn.c
  lib/util.c
  lib/vfs/parse_ls_vga.c
  lib/vfs/path.c
  lib/vfs/utilvfs.c
  lib/widget/input_complete.c
  m4.include/dx_doxygen.m4
  src/filemanager/boxes.c
  src/filemanager/mountlist.c
  src/vfs/cpio/cpio.c
  src/vfs/ftpfs/ftpfs.c
  src/vfs/shell/shell.c
  src/vfs/tar/tar-internal.h
Labels: area: core, prio: medium, state: approved
