Repository MidnightCommander/mc, pull requests merged in 2025-03, with the labels that each got.

#4660 Syntax highlighting of `meson_options.txt` as `meson.build`
  misc/syntax/Syntax.in
Labels: area: mcedit, prio: medium

#4662 maint: explicitly compare preset issue type names in labeler workflow
  .github/workflows/process-incoming-issues.yml
Labels: area: adm, prio: medium

#4663 Fix kitty keyboard protocol parsing of ctrl-o
  lib/Makefile.am
  lib/terminal.c
  lib/terminal.h
  lib/util.c
  lib/util.h
  src/filemanager/layout.c
  src/learn.c
  src/setup.c
  src/subshell/common.c
  tests/.gitignore
  tests/lib/Makefile.am
  tests/lib/terminal.c
Labels: area: tty, prio: high, ver: 4.8.33

#4666 Fix manual pages and online rendering
  .github/workflows/ci-fedora.yml
  .github/workflows/ci.yml
  .github/workflows/update-sources.yml
  doc/man/es/mc.1.in
  doc/man/hu/mc.1.in
  doc/man/it/mc.1.in
  doc/man/mc.1.in
  doc/man/mcdiff.1.in
  doc/man/mcedit.1.in
  doc/man/mcview.1.in
  doc/man/pl/mc.1.in
  doc/man/ru/mc.1.in
  doc/man/sr/mc.1.in
  maint/doctest
  maint/doctest.py
  maint/mandoc-1.14.6.css
Labels: area: docs, prio: high, state: approved

#4667 Use display charset to match patterns in mc config files
  lib/filehighlight/ini-file-read.c
  src/editor/syntax.c
  src/filemanager/ext.c
  src/usermenu.c
  src/vfs/sftpfs/config_parser.c
  tests/src/Makefile.am
  tests/src/editor/Makefile.am
  tests/src/editor/edit_replace_cmd.c
  tests/src/filemanager/Makefile.am
  tests/src/fixtures/hints/mc.hint
  tests/src/fixtures/mc.charsets
  tests/src/fixtures/viewertest.txt
  tests/src/usermenu__test_condition.c
Labels: area: core, prio: medium, state: approved

#4672 Improve issue template
  .github/ISSUE_TEMPLATE/1-bug.yml
  .github/ISSUE_TEMPLATE/2-feature.yml
Labels: area: adm, prio: medium

#4671 Ticket #4670: customize error message when `known_hosts` file cannot …
  src/vfs/sftpfs/connection.c
Labels: area: vfs, prio: medium, state: approved

#4679 Ticket #4678: `usqfs` parser ignored first 4 lines of the file listing
  src/vfs/extfs/helpers/usqfs.in
  tests/src/vfs/extfs/helpers-list/data/usqfs.output
Labels: area: vfs, prio: medium
