Repository MidnightCommander/mc, pull requests merged in 2025-06, with the labels that each got.

#4718 Ticket #4715: fix basic heredoc highlighting for shell syntax
  misc/syntax/sh.syntax
Labels: area: mcedit, prio: medium, state: approved

#4724 subshell: reorder pty/pipe file descriptor acquisition
  src/subshell/common.c
Labels: area: core, prio: medium, ver: 4.8.33

#4725 User menu: select first item that matches the condition, not second
  src/usermenu.c
Labels: area: core, prio: medium
